from dandiscribe.enums import HAlign as HAlign, VAlign as VAlign
from dataclasses import dataclass
from functools import lru_cache
from typing import NamedTuple

@dataclass
class Align:
    vertical: VAlign = ...
    horizontal: HAlign = ...

class Margins(NamedTuple):
    top: float
    right: float
    bottom: float
    left: float
    @property
    @lru_cache
    def horizontal(self) -> float: ...
    @property
    @lru_cache
    def vertical(self) -> float: ...
    def with_top(self, top_val: int): ...
    def with_right(self, right_val: int): ...
    def with_bottom(self, bottom_val: int): ...
    def with_left(self, left_val: int): ...
