import types
from dandiscribe.data import Margins as Margins
from dandiscribe.enums import PAGESIDE as PAGESIDE
from dandiscribe.exceptions import InvalidSheet as InvalidSheet
from dandy_lib.datatypes.twodee import Size
from dataclasses import dataclass
from functools import lru_cache
from typing import NamedTuple

class Page(NamedTuple):
    page_number: int
    size: Size = ...
    master_page: str | None = ...
    is_master: bool = ...
    def __post_init__(self) -> None: ...
    def as_page(self) -> Page: ...
    def as_master_page(self) -> Page: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def make(self) -> None: ...
    def draw(self, master: str | None = None): ...

@dataclass(kw_only=True)
class SpreadPage(Page):
    inside_margin: int
    outside_margin: int
    side: PAGESIDE

class Sheet(NamedTuple):
    front: Page
    back: Page
    @lru_cache
    @property
    def size(self) -> Size: ...
