import datetime
import scribus
import types
from dandiscribe.data import Margins as Margins
from dandiscribe.enums import PAGESIDE as PAGESIDE
from dandy_lib.datatypes.twodee import Size
from dataclasses import dataclass, field
from functools import cache as cache, partial

@dataclass
class Page:
    page_number: int
    size: Size = field(default_factory=partial(Size, *scribus.PAPER_A5))
    master_page: str = ...
    is_master: bool = ...
    def __post_init__(self) -> None: ...
    def as_page(self) -> Page: ...
    def as_master_page(self) -> Page: ...
    def get_delta_date(self, days: int = 0, weeks: int = 0) -> tuple[datetime.date, bool]: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def make(self) -> None: ...
    def draw(self, master=None) -> None: ...

@dataclass
class SpreadPage(Page):
    side: PAGESIDE = ...
    def __post_init__(self) -> None: ...
