from _typeshed import Incomplete
from dandiscribe.data import Align as Align
from dandiscribe.enums import FILL as FILL, HAlign as HAlign, VAlign as VAlign
from dandiscribe.style import LineStyle as LineStyle, ParagraphStyle as ParagraphStyle, TextStyle as TextStyle
from dandiscribe.util import TempGoTo as TempGoTo, get_justify_adjustments as get_justify_adjustments, ok_to_ignore_dialog as ok_to_ignore_dialog
from dandy_lib.datatypes.twodee import Size
from dataclasses import dataclass, field
from typing import Callable, ClassVar

logger: Incomplete

@dataclass
class Box:
    rows: int = ...
    sub_rows: int = ...
    row_style: LineStyle = ...
    sub_row_style: LineStyle = ...
    check_boxes: bool = ...
    pre_fill: list[list[str]] = field(default_factory=list)
    align: Align = field(default_factory=Align)
    name: str | None = ...
    pre_fill_style: TextStyle | ParagraphStyle = ...
    pre_fill_max_lines: int | None = ...
    join_lines_with_next: bool = ...
    line_extra_length: int = ...
    draw_cb_func: Callable = ...
    def __post_init__(self) -> None: ...
    def draw(self, x: int, y: int, width: int, height: int, master=None, prefill_from_bottom: bool = False, pre_fill_max_lines: int | None = None): ...

@dataclass
class Checkbox:
    size: Size
    style: LineStyle
    SCRATCH_PAGE: ClassVar[int] = ...
    GOTO1: ClassVar[TempGoTo] = ...
    def draw(self, x: int, y: int) -> str: ...
    @classmethod
    def clean(cls) -> None: ...

def draw_checkbox(x: int, y: int, size: Size, style: LineStyle) -> str: ...

@dataclass
class ColumnSection:
    title: str = ...
    fill: FILL = ...
    background: str | None = ...
    boxes: list[Box] = field(default_factory=list)
    height_rows: int = ...
    title_in_master: bool = ...
    box_align: Align = field(default_factory=Align)
    title_style: TextStyle | ParagraphStyle = ...
    title_min_y: int = ...
    title_line_style: LineStyle | None = ...
    @property
    def rows(self): ...
    def draw(self, x: int, y: int, width: int, height: int, master: bool | None = None) -> str: ...

@dataclass
class Column:
    sections: list[ColumnSection] = field(default_factory=list)
    divider_line: LineStyle = ...
    @property
    def rows(self): ...
    def draw(self, x: int, y: int, width: int, height: int, master=None): ...
