import dandiscribe.colors
import dandiscribe.enums as enums
from _typeshed import Incomplete
from dandiscribe.util import ok_to_ignore_dialog as ok_to_ignore_dialog
from dandy_lib.datatypes.numeric import NonNegInt as NonNegInt
from dataclasses import dataclass, field

ZeroToOnehundredInt: Incomplete
FullIntensity: Incomplete

@dataclass(frozen=True)
class LineStyle:
    weight: NonNegInt
    style: int | None = ...
    def apply(self, obj) -> None: ...

OnePointBlackLine: Incomplete
TwoPointBlackLine: Incomplete

@dataclass
class FillStyle:
    color: dandiscribe.colors.COLORS
    shade: ZeroToOnehundredInt = ...
    def __post_init__(self, shade: ZeroToOnehundredInt = ...): ...

NO_FILL: Incomplete

@dataclass
class ObjectStyle:
    fill: FillStyle

@dataclass(frozen=True)
class TextStyle:
    name: str
    font: str | None = ...
    size: float | None = ...
    features: list[enums.FontFeature] = field(default_factory=list)
    fill_color: enums.COLORS = ...
    stroke_color: enums.COLORS = ...
    def new_with(self, new_name: str, font: str | None = None, size: float | None = None, features: list[enums.FontFeature] = None, fill_color: str = None, stroke_color: str = None): ...
    def setup(self) -> None: ...
    def apply(self, apply_obj) -> None: ...

WEEK_CAL_DAY_HDR_STYLE: Incomplete
WEEK_OF_MAIN_STYLE: Incomplete
MONTH_DATE_TSTYLE: Incomplete

@dataclass
class ParagraphStyle:
    name: str
    linespacing_mode: enums.LinespacingMode = ...
    alignment: enums.HAlign = ...
    vert_alignment: enums.VAlign = ...
    left_margin: int = ...
    right_margin: int = ...
    gap_before: int = ...
    gap_after: int = ...
    first_indent: int = ...
    has_drop_cap: bool = ...
    drop_cap_lines: int = ...
    drop_cap_offset: int = ...
    char_style: TextStyle = ...
    def new_with(self, new_name: str, linespacing_mode: enums.LinespacingMode = None, alignment: enums.HAlign = None, vert_alignment: enums.VAlign = None, left_margin: int = None, right_margin: int = None, gap_before: int = None, gap_after: int = None, first_indent: int = None, has_drop_cap: int = None, drop_cap_lines: int = None, drop_cap_offset: int = None, char_style: TextStyle = None): ...
    def setup(self) -> None: ...
    def apply(self, apply_obj) -> None: ...

WEEK_CAL_TOD_HDR_STYLE: Incomplete
WEEK_CAL_READINGS_STYLE: Incomplete
MONTH_CAL_HEADER_STYLE: Incomplete
MONTH_CAL_HEADER_STYLE_RALIGN: Incomplete
MONTH_CAL_DAY_HDR_STYLE: Incomplete
WEEK_CAL_TASK_STYLE: Incomplete
MONTH_DATE_PSTYLE: Incomplete
GUTTER_HEADER_STYLE: Incomplete

def fill_lined_basic(x, y, width, height, draw_master: bool, line_height: int = 13, line_style: LineStyle = ...): ...

FILLERS: Incomplete
