import types
from _typeshed import Incomplete
from collections.abc import Generator
from contextlib import contextmanager

MISSING: Incomplete

class PauseDrawing:
    @classmethod
    def __enter__(cls) -> None: ...
    @classmethod
    def __exit__(cls, type, value, traceback) -> None: ...

@contextmanager
def save_sandwich(save_as: str | None = None) -> Generator[None, None, None]: ...

class Debug:
    enabled: Incomplete
    entered: Incomplete
    def __new__(cls, debug_id: str, *args, **kwargs): ...
    debug_id: Incomplete
    def __init__(self, debug_id: str, enabled: bool | None = None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    @contextmanager
    def do_break(self, required: bool = False): ...

get_cache_dir: Incomplete
CACHE_FILE: Incomplete

def get_cache_res(): ...
def get_cache_val(key: str, cache_res=None): ...
def cache_val(key: str, value, overwrite: bool = False): ...
def clear_cache_val(key: str): ...
def get_justify_adjustments(count: int, remainder: int) -> list[int]: ...

class NotInDebugger(Exception): ...
class DebuggerNotEnabled(NotInDebugger): ...

class TempGoTo:
    page: Incomplete
    current: Incomplete
    def __init__(self, page: int) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

IGNORED: Incomplete

class _OkToIgnoreDialog:
    ignore_words: Incomplete
    def __init__(self, ignore_words=...) -> None: ...
    def __call__(self, title: str, message: str) -> str | object: ...

ok_to_ignore_dialog: Incomplete
