from functools import cache as cache
from pathlib import PurePath as PurePath
from typing import Any

def existing_path(in_val: str = '.'): ...
def filter_for_attr_val(element, attr: str, value: Any) -> bool: ...
def filter_for_data_hook_value(element, value: str) -> bool: ...
def merge_rcv_block_divs(div1, div2) -> None: ...

class IncorrectAssumptionError(Exception): ...

def get_reciever_div(soup): ...
def main(): ...
