import argparse
from _typeshed import Incomplete
from bs4 import BeautifulSoup
from pathlib import Path as Path, PurePath as PurePath
from typing import NamedTuple

def get_elements(soup: BeautifulSoup, tag: str | None = None, tag_id: str | None = None, tag_class: str | None = None, max_elements=None): ...

class CleanupConf(NamedTuple):
    tag: str
    id: str
    class_: str
    first_page: bool = ...
    remaining_pages: bool = ...
    next_elements: list['CleanupConf'] | None = ...
    def get_elements(self, element) -> list: ...

class AppendAssembled(argparse.Action):
    assembled_type: Incomplete
    def __init__(self, option_strings, dest, nargs=None, **kwargs) -> None: ...
    def __call__(self, parser, namespace, values, option_string=None): ...

def main() -> None: ...
