import re
from _typeshed import Incomplete
from pathlib import Path
from typing import Collection, Iterator

DRIVE_URL_RE: Incomplete
DRIVE_URL_SUB_RE: Incomplete

def dir_path_type(value: str) -> Path: ...
def is_google_drive(url: str) -> bool: ...
def get_drive_id(url: str) -> str: ...
def xform_google_drive(url: str) -> str: ...
def main() -> None: ...
def get_download_links(start_pages: list[str], target_exts: Collection[str] | None = None, target_res: Collection[re.Pattern] | None = None, checked: set[str] | None = None, follow: bool | int = False) -> Iterator[str]: ...
def download_file(url, download_dir: Path, base_filename: str | None = None): ...
